import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/Header';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <ClerkProvider>
         <html lang='en'>
            <body className={inter.className}>
               <Header />
               <main className='container'>
                  <div className='flex justify-center min-h-screen '>
                     <div className='mt-5 w-full shadow-md p-5'>{children}</div>
                  </div>
               </main>
               <Toaster />
            </body>
         </html>
      </ClerkProvider>
   );
}
